Add analog-minimalist
AsteroidOS/unofficial-watchfaces pull request #70
Opened 2022-06-01 11:26 UTC by xattsec

I've made this Minimalist watchface, it was based on "analog-aviator" from eLtMosen.
The "xatt" at the top is not for branding, I just thought it looked cool.

2022-06-01 11:58 UTC, beroset requested changes
Nice first contribution!   It's missing a modification to the README.md file, which should also mention the licensing of the font used and show two preview image as all the other watchfaces have.

2022-06-01 11:58 UTC, beroset commented on analog-minimalist/usr/share/asteroid-launcher/watchfaces-img/analog-minimalist-hour-ambient.svg
> +   sodipodi:docname="analog-minimalist-hour-ambient.svg"
None of this inkscape stuff is relevant to the watch.  You should run these SVG files through `svgo` or export as "Optimized SVG" from inkscape to strip out irrelevant metadata.

2022-06-01 11:58 UTC, beroset commented on analog-minimalist/usr/share/asteroid-launcher/watchfaces-img/asteroid-logo-black.svg
> +l/0RyZNa1tmpOkm2/3EtN/oTADcm+fuW9Sark7QnAH9CukHgZJK/WGoq8O8G9BWtrMN/Fin4i/Dx
More than half the file size is to show "xatt" which doesn't really add much to the design, except perhaps for the author.  I'd recommend omitting it.

2022-06-01 11:58 UTC, beroset commented on analog-minimalist/usr/share/asteroid-launcher/watchfaces/analog-minimalist.qml
> + * Copyright (C) 2021 - Timo Könnecke <github.com/eLtMosen>
If you've made changes to this file, add your own copyright line above this.

2022-06-14 14:06 UTC, FlorentRevest requested changes
+1 to everything beroset said, happy to merge this afterward though

2022-06-14 14:06 UTC, FlorentRevest commented on analog-minimalist/usr/share/asteroid-launcher/watchfaces/analog-minimalist.qml
> +
Unnecessary blank line

2023-02-17 16:02 UTC, closed without merging